### ISSUE TITLE
ブロックスのアルゴリズムを調査

### ISSUE THREAD

**Issue by zonkyy** [ousquid/tableturf-battle-solver#4]

**Comment by MKDir43** [comment]
NSLによるBlokus Duo Multi Game AIシステムの実装: https://www.u-tokai.ac.jp/uploads/sites/12/2021/03/PP9-16.pdf

**Comment by MKDir43** [comment]
ブロックスデュオにおける モンテカルロ木探索: https://ipsj.ixsq.nii.ac.jp/ej/?action=repository_action_common_download&item_id=97732&item_no=1&attribute_id=1&file_no=1

**Comment by MKDir43** [comment]
Blokus Game Solver: https://digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1305&context=cpesp

**Comment by koiking213** [comment]
blokusのアルゴリズムは対戦用のため、コンボを探すのには流用できなかった。
