### ISSUE TITLE
カードの持ち方を 2 次元配列から座標の set に変更する

### ISSUE THREAD

**Issue by zonkyy** [ousquid/tableturf-battle-solver#5]
A: (1, 1), (1, 2)

B: (3, 1), (3, 2)

B!: (2, 1), (4, 1), (3, 0), (3, 2), (2, 2), (4, 2), (3, 1), (3, 3) - B

B! は B の隣接座標

A と B でかぶるものがない、かつ、A と B! でかぶるものがある場合隣接してると言える。

**Comment by koiking213** [comment]
Patternクラスを新たに作成し、CardやPlacementクラスの処理を置き換えた
次回、Stageクラスのget_sliceを廃止し、オフセットの加算はget_patternで行う。

**Comment by MKDir43** [comment]
* get_sliceは、ndarrayの参照範囲削減のための処理、set(Cell)では包含判定のみなので不要。
* get_patternでplace.point分のオフセットをして、カード座標系からstage座標系に変換。

**Comment by zonkyy** [comment]
(tuple-core ブランチを使用していることに注意)

**Comment by koiking213** [comment]
neighbor_pattern中で、set(Cell)の積集合が正しく取れないバグが解決できていない。

- card_patに(3,3)が含まれるとき、Cell(Point(3,3), False), Cell(Point(3,3), True)共にcard_patには含まれないと判定される
- hash値を見ると、card_pat中の(3,3)とCell(Point(3,3))は同じ

**Comment by koiking213** [comment]
https://github.com/ousquid/tableturf-battle-solver/commit/ab7534ffaa4cb57972a57cafa1677c3b2d273d02 で解決
