### ISSUE TITLE
高速化

### ISSUE THREAD

**Issue by koiking213** [ousquid/tableturf-battle-solver#8]
ステージの大きさを、今置こうとしているカードと今の盤面に必要な最小サイズにする

**Comment by MKDir43** [comment]
* numba
* cython
とか使ってみる

**Comment by koiking213** [comment]
- pypyを使うとお手軽に速くなった(13~14倍ぐらい？)
- 「ステージの大きさを、今置こうとしているカードと今の盤面に必要な最小サイズにする」は1.5倍ぐらい速くなった
